### PR TITLE
Removed unused code. Separated device requests. Added device decorator.

### PR DESCRIPTION
**Pull request by tibawatanabe**
I'm writing here almost everything I did. You don't have to accept this PR, this is just to guide you.
##### Highlights
- I've change some parts to use the Heroku server, so you're still developing with json.server, this code might not be fully reusable (at least the devices code).
- Though I'm explaining piece by piece, it may not be possible to follow exactly these steps, since there are a lot of code changed during this refactor.
# Code Cleanup
## Require's paths

The first thing we can do is change `require` paths. Instead of writing `../src/...` or `./...` we can simply write `src/...` (we could omit `src`, but to avoid collisions, we are keeping it). 

For instance, we can rewrite this:

``` coffee
router_module = require('../src/router')
```

like this:

``` coffee
router_module = require('src/router')
```

And it does not matter we use it because of [rootpath](https://github.com/fabriziomoscon/rootpath) (found in `index.js`).
## Unused files / references

The next thing we can do is remove all unused files. I've dug a little bit and discovered that `configHelper`@`bot.coffee` is not been used by `config` at all. There is no reference to it in the code. This helper have some nice features but since we are not using it, I've decided to remove it. The same can be applied to `router.coffee` and `handler.coffee`.
## `require`

I've notice that the original code was like this:

``` coffee
awesome_module = require './awesome'
awesome = awesome_module async, config, router_module
```

The first line was used by the second line, and only there. Instead, we can simplify these lines with this one:

``` coffee
awesome = require('src/awesome') async, config, router_module

# or

awesome = require('src/awesome')(async, config, router_module)
```
## CoffeeScript

CoffeeScript allows developers to omit a lot of things like `return`, `;`, `(`, `)`, ...

Though this makes code cleaner (for some at least), it also makes difficult for beginners to understand, specially if one has already learned a more traditional language.
### Omitting `return`

In some blocks (like function bodies), the last line is a return statement.

So this code here:

``` coffee
myFunc = () ->
  10
```

is similar to this:

``` coffee
myFunc = () ->
  return 10
```

This is specially confusing when you have a function with lots of code (i.e a module) and at the end you find something like this:

``` coffee
module.exports = () ->
  # lot of code

  myCommand = () ->
    # more code here

  # hundreds of line
  execute: myCommand
```

which is equivalent to this:

``` coffee
module.exports = () ->
  # lot of code

  myCommand = () ->
    # more code here

  # hundreds of line
  return {
    execute: myCommand
  }
```
### Useless code

I've found this piece of code repeated in `awesome.coffee`

``` coffee
someFunc arg1, cb
(response, cb) ->
  return cb null, response
```

which produces this:

``` javascript
someFunc(arg1, cb);

(function(response, cb) {
  return cb(null, response);
});
```

As you can see, the last two lines are useless.
#### Tip

In order to check the javascript equivalent you can use Try CoffeeScript at [CoffeeScript page](http://coffeescript.org/)
### String concatenations
- This is one thing I like about CoffeeScript. Instead of writing
  
  ``` coffee
  say = "anything"
  "Something I want to say is: " + say
  ```
  
  we can simplify like this:
  
  ``` coffee
  "Something I want to say is: #{say}"
  ```
  
  Oh, this only works with double quote`"`.
- And this is a Javascript way of concatenating several strings (by using `Array.join`):
  
  ``` coffee
  myStringList = [
    "First line"
    "Second line"
  ]
  myMultilineString = myStringList.join '\n'
  # myMultilineString is equal to "First line\nSecond line"
  ```
# Architecture

I've separated a little bit the code. Instead of requesting in `awesome.coffee` I've created a separated module to do all requests.

Additionally, I've created a decorator to inject some functions in `device` object.
## Devices

This is a very simple module. It basically has all http operations needed for `awesome-bot`.

One thing to notice is that instead of checking a specific code for `responseCode` I've made a range validation. Theoretically, from `200` to `299` should be success code. Here is a [nice list](https://httpstatuses.com/)
## Device decorator

Javascript has a nice (sometimes, not always) feature of adding properties on the fly. As consequence we can add a function, or property to an existing object and use it later, like this:

``` coffee
device =
  os: 'ios'
  name: 'iPhone'

decorate(device)

device.print() # results in "ios iPhone"

# somewhere in the code, or in another module
decorate = (device) ->
  device.print = () ->
    "#{device.os} #{device.name}"
```

### CODE REVIEW

**Comment by tibawatanabe** [comment]
@dandpb @LeticiaTiemi as reference

**Comment by tibawatanabe** [comment]
@dandpb @LeticiaTiemi CR 😄

**Comment by felipesabino** [comment]
@tibawatanabe @LeticiaTiemi This PR is very old, can it be merged? 

If not, can you add a comment with what is still pending to be merged or just close it and delete the branch?

**Comment by askmon** [comment]
@felipesabino No, the refactor was already made on other PRs, I just left it here for further consulting. But perhaps I think that nobody will see it anymore haha I'll leave it closed

**Pull request closed without merging**
